Resources:
  SageMakerExeuctionRole50A8DBE3:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - sagemaker.
                    - Ref: AWS::URLSuffix
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonSageMakerFullAccess
    Metadata:
      aws:cdk:path: prod-sagemaker-stack/SageMakerExeuctionRole/Resource
  SageMakerExeuctionRoleDefaultPolicy15F3758D:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:ListBucket
            Effect: Allow
            Resource:
              - arn:aws:s3:::SageMaker
              - arn:aws:s3:::sagemaker/*
          - Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:CreateBucket
            Effect: Allow
            Resource:
              - arn:aws:s3:::SageMaker/*
              - arn:aws:s3:::sagemaker/*
          - Action: iam:GetRole
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: SageMakerExeuctionRoleDefaultPolicy15F3758D
      Roles:
        - Ref: SageMakerExeuctionRole50A8DBE3
    Metadata:
      aws:cdk:path: prod-sagemaker-stack/SageMakerExeuctionRole/DefaultPolicy/Resource
  SageMakerWorkshopA220E036:
    Type: AWS::IAM::Group
    Properties:
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonSageMakerFullAccess
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AWSCloud9Administrator
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/CloudWatchLogsReadOnlyAccess
    Metadata:
      aws:cdk:path: prod-sagemaker-stack/SageMakerWorkshop/Resource
  SageMakerWorkshopDefaultPolicy63CD0CD3:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:ListBucket
            Effect: Allow
            Resource:
              - arn:aws:s3:::SageMaker
              - arn:aws:s3:::sagemaker/*
          - Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:CreateBucket
            Effect: Allow
            Resource:
              - arn:aws:s3:::SageMaker/*
              - arn:aws:s3:::sagemaker/*
        Version: "2012-10-17"
      PolicyName: SageMakerWorkshopDefaultPolicy63CD0CD3
      Groups:
        - Ref: SageMakerWorkshopA220E036
    Metadata:
      aws:cdk:path: prod-sagemaker-stack/SageMakerWorkshop/DefaultPolicy/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.0.0,@aws-cdk/aws-iam=1.0.0,@aws-cdk/core=1.0.0,@aws-cdk/cx-api=1.0.0,@aws-cdk/region-info=1.0.0,jsii-runtime=node.js/v10.16.0

